server:
  port: 6666
spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 890505
  cloud:
    gateway:
      routes:
      - id: sso-client
        uri: lb://SSO-CLIENT
        order: 0
        predicates:
        - Path=/SSO-CLIENT/**
        filters:
        - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
