spring:
  profiles:
    active: dev1
---
spring:
  profiles: dev1
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
#    hostname: eurekaServer1
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://server2:8762/eureka/,http://server1:8762/eureka/
---
spring:
  profiles: dev2
  application:
    name: eureka-server
server:
  port: 8762
eureka:
  instance:
    hostname: eurekaServer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server1:8761/eureka/,http://server1:8763/eureka/
---
spring:
  profiles: dev3
  application:
    name: eureka-server
server:
  port: 8763
eureka:
  instance:
    hostname: eurekaServer3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server1:8761/eureka/,http://server1:8762/eureka/
