spring:
  profiles:
    active: dev
server:
  port: 9999
---
spring:
  profiles: dev
  application:
    name: config-center
  cloud:
     config:
      server:
       default-label: dev
       jdbc:
        sql: SELECT akey , avalue FROM config_server where APPLICATION=? and APROFILE=? and LABEL=?
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/test
     username: root
     password: 890505
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
